### ISSUE TITLE
Code Style Guide for CodeYourFuture

### ISSUE THREAD

**Issue by ChrisOwen101** [CodeYourFuture/syllabus#105]
**What is the work that needs to be done?**

In the wild, there are lots of good Code Style guides that can help us to make sure our student code in professional way. 

The problem with many corporate-grade guides is that they are very dense and assume an advanced knowledge of JavaScript - not ideal for our students when they're starting out.

For inspiration here is [AirBnBs](https://github.com/airbnb/javascript). 

**Why is this work important to do?**

We often tell our students to "write good code" but our definition of that is sparse and disparate. This file will become our single source of truth for what we expect of our students.

**Additional context**

A very acceptable version of this would be a pared-down version of a corporate style guide with links away to the full document.

**Comment by textbook** [comment]
I set up an ESLint configuration: [`@codeyourfuture/eslint-config-standard`](https://www.npmjs.com/package/@codeyourfuture/eslint-config-standard). This is in use in the [final project starter kit](https://github.com/CodeYourFuture/cyf-final-project-starter-kit) and the [CYF CRA template](https://www.npmjs.com/package/@codeyourfuture/cra-template) (plus some of my own personal projects!) It's quite opinionated, but hopefully that reduces the number of different ways to write the "right" code, and it lays out the principles that drive those choices.

**Comment by nbogie** [comment]
Contemplating the usability of @textbook 's rules from day 1, I see nothing that would be troublesome for even one's first javascript programs (assuming eslint would be configured to auto-format).

If students want to learn by pasting examples from tutorials and other sources, at least `no var` might be problematic until they've learned they can replace var with let in most cases.  (Their programs in the fundamentals course use var, for example, but they do those in a completely different (online) IDE, and I wouldn't expect them to be working on them in vscode.)

**Comment by illicitonion** [comment]
We should make sure that all of our homework and classwork exercises are prettier-formatted so that students don't auto re-format them on submission :)

(Maybe via a GitHub action)

**Comment by 40thieves** [comment]
I've taken a crack at scoping this one out, and come up with the proposal.

### Tools

The less reading that students need to do to produce correct code, the more likely they are to succeed. Therefore, how well could we automate a solution with tooling?

- Prettier installed in [student setup instructions](https://docs.codeyourfuture.io/course-processes/before-the-course/getting-setup#3-visual-studio-code)
  - We should ensure that it's configured to run-on-save
  - IMO we can rely on Prettier for solving most of the problems we see with student code in JS 1/2/3
  - Should we use a Github Action to enforce Prettier rules?
    - We would have to teach students how to find and interpret the error messages. Reading CI logs is a skill too! Because of this, I'm not convinced that it's worth the tradeoff
      - But if someone wants to give it a shot, I wouldn't be against it
- ESLint installed in [student setup instructions](https://docs.codeyourfuture.io/course-processes/before-the-course/getting-setup#3-visual-studio-code)
  - However, the ESLint extension doesn't come with a set of rules. So we'd have to install them in every repo
  - [Jon's rules](https://www.npmjs.com/package/@codeyourfuture/eslint-config-standard) seem reasonable to me, however I think some are nitpick-y enough that they aren't worth the overhead of installing the rules for JS1/2/3
    - I do think they are useful for modules beyond JS3
    - I do like that there is some reasoning provided for each of the rules, although I wonder if this could be made clearer for students?
  - Potential idea: create a VSCode plugin with the rules installed too?

Therefore my conclusion is for JS1/2/3, we can rely on Prettier to cover a large portion of a student style guide. From the React module onwards, I would lean towards either using built-in tooling (like Create-React-App), or Jon's rules above.

### Explanation of Prettier

Having said that, I do think there is value in briefly documenting what Prettier is and what it does. E.g.

- "Prettier is a tool that re-arranges your code"
- "Red squiggly lines mean you have written the code incorrectly. Try looking for missing brackets"
- "If you get a surprising reformat, it may mean that your code is incorrect. Try re-reading it carefully to make sure you haven't made any mistakes"
  - This is to cover technically valid syntax, but incorrect logic e.g.
  ```js
  return;
  {
    foo: 'bar'
  };
  ```

### Non-formatting related rules for JS1/2/3

I also think there is value in documenting some non-formatting related rules that Prettier does not cover. Here's a (non-exhaustive) list of things I think we should cover:

- Indentation
  - This is largely handled by Prettier, but I think we should give a quick explanation of why it's important to indent properly
    - Students do sometimes write in environments which don't run Prettier automatically
- No unused variables
  - Can be confusing
- Don't leave lots of commented out code
  - Students often do this as puesdo version control
  - When there is lots of it, it can be confusing
  - We should instead encourage them to commit often instead, so they have "safe" versions of their code
- Good naming
  - Do we have existing materials on this?
    - Should this be discussed in class?
  - Ideas
    - camelCase
    - Avoid short names
    - Descriptive of what it is/what it does
    - Communication to another programmer

### Out of scope

I think we should stay away from covering how to use specific language features, which are common in corporate style guides. I am wary of this document turning into a JS cheatsheet (to be clear, I'm not against that existing :slightly_smiling_face:) and becoming too long or intimidating to beginners.

As an example, I *don't* think we should cover preferring  `===`/`!==` over `==`/`!=`. It is [covered in the syllabus](https://syllabus.codeyourfuture.io/js-core-1/week-2/lesson#comparison-operators), and I think it should be framed as "correct vs incorrect syntax".

### Summary

Sorry for the long post, here's the tl;dr:

- Ensure we install Prettier & configure it to run-on-save
- Write a short explanation of what Prettier is and what it does
- Write some general advice (not particularly specific to JS) as a "style guide" (this can be in the same document)

What do you think? Feedback welcome!

**Comment by illicitonion** [comment]
> I've taken a crack at scoping this one out, and come up with the proposal.

I like it, I think I agree with it all.

> ### Tools
> The less reading that students need to do to produce correct code, the more likely they are to succeed. Therefore, how well could we automate a solution with tooling?
> 
> * Prettier installed in [student setup instructions](https://docs.codeyourfuture.io/course-processes/before-the-course/getting-setup#3-visual-studio-code)
>   
>   * We should ensure that it's configured to run-on-save
>   * IMO we can rely on Prettier for solving most of the problems we see with student code in JS 1/2/3
>   * Should we use a Github Action to enforce Prettier rules?
>     
>     * We would have to teach students how to find and interpret the error messages. Reading CI logs is a skill too! Because of this, I'm not convinced that it's worth the tradeoff

I think definitely not worth the trade-off, at least in JS1 and JS2 - maybe JS3 could be a reasonable place to fold that in... When giving homework feedback, I very consciously don't mention style things for learners who are clearly struggling with basic concepts (where style wouldn't help - if naming / indenting their code better would help them write code better, I'll mention it), and start folding in style suggestions as they're becoming more comfortable with the basics. A GitHub Action wouldn't allow scope for that nuance unless we told them something like "Ignore this red cross telling you there's a problem", which is a bad habit to instil :)

**Comment by 40thieves** [comment]
PR up now: https://github.com/CodeYourFuture/syllabus/pull/156
