### ISSUE TITLE
Add More JS2-2 Coursework

### ISSUE THREAD

**Issue by ChrisOwen101** [CodeYourFuture/syllabus#120]
**Which module(s) and week(s) does this change effect?**
Module(s): JavaScript Core 2
Week(s): Week 2

**What is the work that needs to be done?**

This week is pretty light on coursework for exercises and challenges which means our students don't get a lot of practice doing the work this week.

This ticket should add a few more smaller exercises and one larger project for the students to work on this week. 

Please make sure to check what the students have learnt in this lesson. If you want to include challenges that the students haven't learnt yet, please tag them as `(Optional)`

**Why is this work important to do?**

This is the week that the DOM and DOM manipulation is introduced and is quite pivotal. It's pretty important that the students get a good amount of practice doing this work before they move on to the next week 

**Additional context**

Homework page: https://syllabus.codeyourfuture.io/js-core-2/week-2/homework
Homework repo: https://github.com/CodeYourFuture/JavaScript-Core-2-Coursework-Week2

**Comment by 40thieves** [comment]
Not sure if this is too large: https://github.com/CodeYourFuture/group-project-bookshelf or https://github.com/CodeYourFuture/group-project-dom-payments (they're labelled group projects but they don't necessarily have to be)
