### ISSUE TITLE
bad link for "postgresql preparation" in db/week-1/instructors

### ISSUE THREAD

**Issue by nbogie** [CodeYourFuture/syllabus#154]
**Describe the bug**

The link to "PostgreSQL Preparation" from db module week 1 instructor notes yields 404

**What is wrong with this content?**
bad link

**How could this be fixed?**
put good link

**Link to content**
https://syllabus.codeyourfuture.io/db/week-1/instructors

**Additional context**

**Who else might need to know about this?**

**Comment by nbogie** [comment]
on investigation looks like the intended-linked document hasn't been committed to master - only in branch SQL-Prep: 
https://github.com/CodeYourFuture/syllabus/blob/SQL-Prep/docs/db/prep.md

**Comment by SallyMcGrath** [comment]
looks solved!
