### ISSUE TITLE
Include early homework task to back up personal files

### ISSUE THREAD

**Issue by nbogie** [CodeYourFuture/syllabus#159]
**Which module(s) and week(s) does this change effect?**
Module(s): Intro
Week(s): 1

**What is the work that needs to be done?**

Set a homework task into the syllabus in which the students identify and back up all of their important personal files.

Here's a minimal google classroom post (based on what I set for London class 6):
```
Make a backup of all of your essential files (i.e. files you would be unhappy to lose) from your laptop (the one you use for CYF work), to a DIFFERENT device.

Example places you can back up to:
==============================
The cloud (e.g. google drive, or dropbox), 
Another computer
An external hard disk 
A USB stick
etc...

You MUST NOT back-up the files simply to another folder in the same laptop

You will probably have to research online to find your solution
```

**Why is this work important to do?**

Prepares the student for the possibility that their or machine gets stolen, or their drive gets wiped/corrupted (possibly as a result of an over-enthusiastic CYF TA helping them to upgrade OS or misuse rm command), 

Gives us a position of confidence from which to recommend/mandate any necessary OS installs / updates / drive repartitions, other software installs, etc.

**Additional context**

**Who might need to know about this change?**

**Comment by ChrisOwen101** [comment]
This has been added to our Getting Setup guide that is given to every student before they start the Full Stack course

https://docs.codeyourfuture.io/course-processes/before-the-course/getting-setup
