### ISSUE TITLE
Add "Create Cowsay" as Coursework

### ISSUE THREAD

**Issue by ChrisOwen101** [CodeYourFuture/syllabus#162]
**Which module(s) and week(s) does this change effect?**
JS1-3 or JS2-1

**What is the work that needs to be done?**

@40thieves mentioned [CowSay](https://alligator.io/workflow/cowsay/) in a call the other day.

@illicitonion noticed that it would make a nifty coursework if it was ran with node with arguments in the command line.

The result of this ticket should be 

- Coursework in the form of a markdown file with the task
- Starter code for the student to base their work on
- A sample solution
- (If possible) some kind of automated tests that check to see if it is working correctly

In the link above it also mentions `CowThink` which could be an interesting permutation based on a command line argument.

**Why is this work important to do?**

More, interesting, coursework is always good for our students

**Comment by 40thieves** [comment]
Only thing I would add is a stretch goal of a different animal, mostly just for fun 🙂
