### ISSUE TITLE
JS-1 Week 3: push, pop, shift and unshift array methods are missing from the lesson content

### ISSUE THREAD

**Issue by szemate** [CodeYourFuture/syllabus#173]
**Which module(s) and week(s) does this change effect?**
Module(s): JS-1
Week(s): 3

**What is the work that needs to be done?**

The [Array methods](https://syllabus.codeyourfuture.io/js-core-1/week-3/lesson#array-methods) section of the lesson doesn't cover `push`, `pop`, `shift` and `unshift` methods. The slides attached to the lesson include these, therefore I assume that they should be part of the lesson, but those teachers who don't teach from slides can easily forget about them.

**Why is this work important to do?**

These are possibly the most commonly used array methods, it is important that the students hear about them in class.

**Comment by SallyMcGrath** [comment]
I think that perhaps we shouldn't teach these actively, in accordance with our functional programming paradigm, as they are all array mutators.

@illicitonion @ChrisOwen101  what do you think?

**Comment by szemate** [comment]
> I think that perhaps we shouldn't teach these actively, in accordance with our functional programming paradigm, as they are all array mutators.

I believe trainees still need to hear about these methods as they should understand what array mutation is. At most workplaces (code bases) they will encounter these methods.

**Comment by SallyMcGrath** [comment]
They will encounter them, for sure, but I think it's a mistake to load them up with syntax at this point. I don't think they should be part of the core lesson. They are not forbidden knowledge, but I don't think we should focus on them or put them in the core content.
