### ISSUE TITLE
Update week 2 homework text in repo

### ISSUE THREAD

**Issue by ultraasi-atanas** [CodeYourFuture/syllabus#179]
**Which module(s) and week(s) does this change effect?**
Module(s): HTML CSS 
Week(s): Week 2

** What is the work that needs to be done? **

Students submit non-responsive solutions and tutors cannot push back because of the wording in the task Readme which is not suggesting the solution needs to be responsive. Also students who miss the in-class homework instructions, due to illness etc, only rely on the homework text as a guidance  E.g.

- [ ] 1. The aim of this exercise is to create a page that looks "just like this one"
- [ ] 2. Edit `index.html` and `style.css` "to re-create the design above".
- [ ] 3. use semantic HTML to re - create the structure, and style each element using CSS "to make a perfect copy of the above image"

The current homework text for week 2 might be left over from previous versions of the module taught by @LucyMac 

> I actually start off with the Karma project from week 1. First we do these exercises in class https://codesandbox.io/s/z69nnxv5q3?file=/index.html in small groups throughout lesson 1. Practises both semantic HTML and basic CSS.
> Then Karma is the week 1 homework, which we fork, clone and set up at the end of lesson 1, and which students need to complete (desktop only) by lesson 2.
> Then in week 2, we use Karma as in-class practice to learn about media queries, and start the Cakes project (also recently updated) as week 2 homework: https://github.com/CodeYourFuture/HTML-CSS-Coursework-Week3

**Why is this work important to do?**

Creative disagreements arise during debating whether submissions are valid if they are not responsive.
Students migth ask questions.

** Additional context **

**Who might need to know about this change?**

Syllabus team & @ChrisOwen101

**Comment by LucyMac** [comment]
I've been using this exercise as the homework for week 1, which is why it doesn't mention responsiveness.

We learn about media queries in week 2 and add some media queries to this project as an in-class exercise in week 2, to be perfected as homework.

Main responsive homework for week 2 is the cake wireframe.

Apologies for any confusion - hopefully the upcoming review/restructure of the html and css module can iron this out.

**Comment by ultraasi-atanas** [comment]
Thank you very much!
I will let the SA team know
