### ISSUE TITLE
Adding exercise to 'How does the web work?'

### ISSUE THREAD

**Issue by bec-gray** [CodeYourFuture/syllabus#193]
**Which module(s) and week(s) does this change effect?**
Module(s): JS Core 2
Week(s): 3

**What is the work that needs to be done?**

Adding an interactive exercise to the 'How does the web work?' section. Currently there are some great diagrams and explanations of the different components, but there are mostly just talked through by the class leader. I am proposing that we (myself and Matt Compton) create an interactive exercise using a diagram-based drawing program like Lucidchart. The components would all be given in a random arrangement, and together the students and TAs could connect them 'build the internet'. 

**Why is this work important to do?**

I think this exercise will help people understand the different components, their purpose and how they interact in a more interactive format than the current treatment in the syllabus. Additionally, the preceding section of the class involves some very challenging exercises on callback functions, and I think having this simple exercise right after will help to boost people's confidence and get them re-engaged with the lesson.

**Additional context**

**Who might need to know about this change?**

I'm sorry, I'm not really sure!

**Comment by SallyMcGrath** [comment]
@ChrisOwen101 is this done? I can't see it anywhere
