### ISSUE TITLE
Scotland Fundamentals Branch

### ISSUE THREAD

**Issue by anthonygerrardlrng** [CodeYourFuture/syllabus#194]
Fundamentals

Create new Fundamentals Course branch for Scotland Class 5

After reviewing the Fundamentals syllabus it was felt by the Scotland team that there were some small issues that may impact our ability to deliver this successfully for both students and volunteers. We therefore propose to create a temporary Scotland Fundamentals branch to refer Scotland Class 5 students to, with a slimmed down syllabus that doesn't deviate too much from the current syllabus but feels like it will be a lot less overwhelming for the students and easier for the volunteers to manage too. The other recommendation will be to re-word the parts that uses language/tone that suggest this is a pre-assessment course, to make it a lot more encouraging without losing the emphasis that we do need the students to commit to the course fully.

@ChrisOwen101 @zero-point @alastair87 

Programme changes: https://docs.google.com/spreadsheets/d/1q8wArmH1qqHDuw9HxE_EM3K9Qa9VlMIwYI8ylbmvdL0/edit?usp=sharing

Additional notes: An hour of live coding on weeks 3 and 4 seems like quite a lot, and sounds like it could potentially be a little boring. Might be possible to integrate the algorithm recipe with one of the live coding sessions, so the students develop a recipe and the instructor live-codes it?

Language changes: https://docs.google.com/document/d/1kqmA-k41vfdVRTAmdtLspMCfi5g4ET-0xIp3Ld9Q03Y/edit?usp=sharing

**Comment by illicitonion** [comment]
The language changes look wonderful :) Thanks!
