### ISSUE TITLE
Add `pgexercises.com` to the PostgreSQL Module Corusework

### ISSUE THREAD

**Issue by ChrisOwen101** [CodeYourFuture/syllabus#195]
**Which module(s) and week(s) does this change effect?**
Module(s): PostgreSQL
Week(s): 1,2,3

**What is the work that needs to be done?**

This website

PostgreSQL has a fantastic set of exercises that teach Postgres in the browser - ideal for our students. 

They should be added as coursework for Weeks 1,2 and 3 with the relevant exercise depending on what is covered that week. Students should also be encouraged to learn move using the website as they wish.

**Why is this work important to do?**

Postgres is a module that has been quite hard to teach because students have to do a lot of setup on their machines before they can start learning. There's a lot of "Dont worry about this, just follow these steps".

These exercises should help that since you can run everything in the browser

**Additional context**

**Comment by SallyMcGrath** [comment]
https://pgexercises.com/questions/basic/
