### ISSUE TITLE
Add solutions to in-class exercises in-line

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/syllabus#217]
**Which module(s) and week(s) does this change effect?**
Module(s): All, but we're going to start with JS2 week 1
Week(s): All

**What is the work that needs to be done?**

Wherever we have exercises, we should also write down the answers. We chatted in the syllabus team meeting and decided:
1. Ideally these would be a second tab in-line in the syllabus page alongside each exercise.
2. In the future we may want to put in a not-very-clever password dialogue so that we can give the trainees a password at the end of each class so that they aren't tempted to view the solutions before the class finishes. We wouldn't be aiming to be secure, here, just slightly inconvenient.

**Why is this work important to do?**

So that trainees have a helpful reference/guide to help them recap what they've just been taught, and to help them work out their homework.

**Additional context**

@ChrisOwen101 is going to put together resources/an example for how to do the multiple tab thing, to support @makanti in porting the solutions in https://github.com/CodeYourFuture/syllabus/pull/182 to appear as tabs.

We may or may not get around to the passwordy thing in the future, but we definitely don't want to block on it before starting to get the solutions in people's hands.

**Comment by 40thieves** [comment]
> We may or may not get around to the passwordy thing in the future

Very basic sketch that should work: https://codesandbox.io/s/exercise-answers-component-c7nkk?file=/src/App.js (it's untested with MDX though)

**Comment by 40thieves** [comment]
Raised a PR to allow "lockable" solutions via a MDX react component: https://github.com/CodeYourFuture/syllabus/pull/223

**Comment by SallyMcGrath** [comment]
@all-contributors please add @illicitonion
