### ISSUE TITLE
React Week 2: setting state based on previous state not taught correctly 

### ISSUE THREAD

**Issue by chrisdrifte** [CodeYourFuture/syllabus#224]
The syllabus consistently uses examples that change state based on previous state that are not correct (according to my understanding). There are multiple, but the first block of code with this issue is below:

```js
function Counter() {
  const [count, setCount] = useState(0);

  function incrementCount() {
    setCount(count + 1); // this line is wrong, it should be setCount(count => count + 1);
  }

  return (
    <div>
      <button onClick={incrementCount}>Click me</button>
      <p>You clicked {count} times</p>
    </div>
  );
}
```

**What is wrong with this content?**

I have created [some example code](https://codesandbox.io/s/broken-state-changes-88em7?file=/src/index.js) illustrating why this approach doesn't work, and you can also [read the react docs](https://reactjs.org/docs/state-and-lifecycle.html#state-updates-may-be-asynchronous) for the official recommendation.

**How could this be fixed?**

Replace all instances where state is updated based on previous state to use arrow functions instead of references to locally scoped variables. Add a paragraph to make it clear to students that arrow functions should always be used when changing state based on previous state.

**Link to content**

https://syllabus.codeyourfuture.io/react/week-2/lesson/

**Comment by chrisdrifte** [comment]
After @40thieves explained that the syllabus follows the react docs closely, I opened an issue there https://github.com/reactjs/reactjs.org/issues/3585 which was met with agreement that the react docs explain this point poorly and are being rewritten

**Comment by ChrisOwen101** [comment]
Thanks for Raising @chrisdrifte - I'll bring it into our next sprint

**Comment by 40thieves** [comment]
Update: I've actually come around to the suggestion here and I went ahead and wrote up some suggested changes in this PR: https://github.com/CodeYourFuture/syllabus/pull/274 (please see the description for my thinking).
