### ISSUE TITLE
Name Games: JS-1 and the naming of things

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/syllabus#225]
Which module(s) and week(s) does this change effect?
Module(s): JS Core
Week(s): Week 1 -3

**What is the hypothesis?**

 I've just read through pages and pages of JS-1-W-3 submissions. Students seem to still be quite shaky on the naming of things, even some weeks in to the course. I've written some feedback in the marking guide, but perhaps we can do more to help our students grasp this foundational concept.

**Why is this important?**

We want our students to be loved by their colleagues. ;) 

**Supporting Resources**

Naming and thinking systematically is a big challenge even for professional developers (and it isn't helped by foo and bar, the most stupid of all teaching ideas), but I think we can be a bit imaginative here. How about some group games we can run in the live lesson? I'm thinking something high energy and high impact -- would not want to spend more than 25 minutes on this in a live lesson!

example (very first draft!)

### Game 1: the Outside Context Problem, 25 mins

Split into groups (max 6 including a TA). Each group gets a short function with a clear commented explanation and some random strings, eg:

```js
// Add sales tax to base price on clothes and food. Tax is 25% on clothes and 5% on food. Lists are clothes we sell and food we sell. The function expects a product and a price before tax.
const asHTbN = 0.25;
const dhwioP = 0.05;
let dgshainem = ["shirt", "tie", "hijab", "trousers"];
let hduekmk = ["bananas", "bread", "milk", "chocolate"];

function jkwlamn(aywumdkPP_z, lao0_OOas) {
  if (dgshainem.includes(aywumdkPP_z) || hduekmk.includes(aywumdkPP_z)) {
    if (dgshainem.includes(aywumdkPP_z)) {
      return lao0_OOas * (1 + asHTbN);
    } else {
      return lao0_OOas * (1 + dhwioP);
    }
  } else {
    return "We don't sell that!";
  }
}
```
Spend ten minutes (maximum, set a timer) renaming each nonsense string and submit to exercise leader. The TA should feel free to guide the students through the code but understanding _how_ the code works is not the challenge here. The challenge is to _name_ the parts of the code. Stay in the breakout rooms. Example solution:

```js
// Add sales tax to base price on clothes and food and return the total price. Tax is 25% on clothes and 5% on food. Lists are of clothes we sell and food we sell. The function expects a product and a price before tax.
const CLOTHES_SALES_TAX = 0.25;
const FOOD_SALES_TAX = 0.05;
let clothes = ["shirt", "tie", "hijab", "trousers"];
let food = ["bananas", "bread", "milk", "chocolate"];

function getTotalPrice(product, price) {
  if (clothes.includes(product) || food.includes(product)) {
    if (clothes.includes(product)) {
      return price * (1 + CLOTHES_SALES_TAX);
    } else {
      return price * (1 + FOOD_SALES_TAX);
    }
  } else {
    return "We don't sell that!";
  }
}
```

This part should now be revealed: Leaders, in the main room, quickly make a list of JUST the variable and function names and give this list to another group. Each team then gets five minutes (set a countdown timer) to guess what the code is about from the variable names and nominate someone to say it or paste it in chat. Example list:

```sh
CLOTHES_SALES_TAX
FOOD_SALES_TAX
clothes
food
product
price
getTotalPrice
```

Come back to the main group, go around and share our guesses, now without time pressure. Getting it right _or_ getting it wrong are both great learning opportunities in this exercise. **The purpose of the exercise is learning to think about our own code from the perspective of someone who did not write it and does not know what it does.**

**Comment by Dedekind561** [comment]
This is a really lovely exercise!

**Comment by gregdyke** [comment]
Also really like it. (minor note, "identifier", not "string" - or "name"? "variable name"?)
