### ISSUE TITLE
1. Swap Predicates and Logical Operators in W2, 2. Improve predicates test

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/syllabus#233]
**Which module(s) and week(s) does this change effect?**
Module(s): JS1
Week(s): 2

**What is the work that needs to be done?**

1. A _whole bunch_ of our students don't get the D-predicates exercises and write properly bonkers things. But they do much better on the _same exercise_ in F- logical operators. I think we should do logical operators first and then do predicates, just swap those two around.
2. A big reason it's not clear that their answers are wrong is that the test is testing on false so it passes with junk code. 
```js
function isNegative(number) {
  return typeof banana === "I am an actual banana tho";
}
````
So... we should rewrite these tests on true!

**Why is this work important to do?**

We are getting them in a muddle with true and false here and I can see it's still a problem further in to the course. 

**Additional context**
https://github.com/CodeYourFuture/JavaScript-Core-1-Coursework-Week2/tree/main/exercises/D-predicates
https://github.com/CodeYourFuture/JavaScript-Core-1-Coursework-Week2/tree/main/exercises/F-logical-operators

**Who might need to know about this change?**

**Comment by SallyMcGrath** [comment]
More notes on this. Some absolute madness happening in these submissions eg `return 0<number<10` passes our tests

I think probably if we specify ALL tests MUST have a true and a false case, this will clear this problem up. So could we do instead 

````js
/* 
  DO NOT EDIT BELOW THIS LINE
  --------------------------- */

console.log(`Is 5 negative? ${isNegative(5)}`);
console.log(`Is -5 negative? ${isNegative(-5)}`);
console.log(`Is 5 between 0 and 10? ${isBetweenZeroAnd10(5)}`);
console.log(`Is -5 between 0 and 10? ${isBetweenZeroAnd10(-5)}`);

/* 
  EXPECTED RESULT
  ---------------
  1. Is 5 negative? false 
  2. Is -5 negative? true 
  3. Is 5 between 0 and 10? true 
  5. Is -5 between 0 and 10? false 
*/

**Comment by illicitonion** [comment]
Sounds great!
