### ISSUE TITLE
ESLint rules are too strict for React exercises

### ISSUE THREAD

**Issue by 40thieves** [CodeYourFuture/syllabus#237]
**Describe the bug**

In https://github.com/CodeYourFuture/syllabus/pull/234, we changed the React prep so that trainees install a Create React App via [our template repo](https://github.com/CodeYourFuture/cra-template).

This template adds ESLint rules from https://github.com/CodeYourFuture/eslint-config-standard/ on top of the built-in CRA rules. Some of these rules are overly strict.

**What is wrong with this content?**

Here are the rules that we ran into with London Class 7:

- The `indent` only allows tab indentation. IME the trainees are most used to spaces.
- The `linebreak-style` only allow "Unix" line endings. Trainees using Windows/WSL will encounter errors by default

I believe the intention of these rules was for usage with the final projects, where I can understand the need for strict rules to enforce best practice (in particular the line endings, as code will need to run on multiple different machines). However for the React in-class exercises, we found them a distraction from the teaching.

**How could this be fixed?**

I think the most ideal situation would be to have 2 sets of rules: keep the existing rules for the final project, and a new looser set of rules for in-class exercises.

I am however not sure if this is possible with CRA templating, and so I wonder if the best idea would be to just drop the rules from the template altogether.

**Link to content**

- [Template eslint config](https://github.com/CodeYourFuture/cra-template/blob/61f3d5f50ecbc8ad031991aa2d5c05040ced7b49/generateTemplate.js#L32)
- [Custom eslint rules](https://github.com/CodeYourFuture/eslint-config-standard/blob/ea8650761fff4599ab7facd76fd70dc8cc26e8dc/index.js)

**Additional context**

This came up during the React module for London Class 7

**Who else might need to know about this?**

@DomVinyard 
@textbook

**Comment by textbook** [comment]
> I believe the intention of these rules was for usage with the final projects

Not necessarily, I created the ESLint config as a step towards being consistent throughout the the course (and as a single place to bikeshed the options!) If we're seeing problems I wonder if we should be pushing them "left" rather than "right", i.e. have the trainees reading and writing CYF/standardised code earlier in the process. 

That said, you _can_ have multiple sets of configuration within a plug-in. I was looking at this for adding React-specific rules, which aren't handled by the current config at all. I'd want to be careful how much changed through the course though.

**Comment by textbook** [comment]
In terms of the line endings we could add in auto VS Code setting for that, as I do [here](https://github.com/textbook/starter-kit/blob/master/.vscode/settings.json#L6).

**Comment by 40thieves** [comment]
Just want to say thanks for doing this! And apologies I've only just got back to this.

> If we're seeing problems I wonder if we should be pushing them "left" rather than "right", i.e. have the trainees reading and writing CYF/standardised code earlier in the process.

I think a lot of my opinions here mirror those around testing: since historically we haven't been introducing npm early, it has been hard to enforce.

However I think we're now changing that, so would be probably be in favour of adding linting too. We'd probably need an additional lesson section to ensure that all trainees' machines are correctly configured.

> single place to bikeshed the options

Since you brought it up... I would suggest switching from tabs to 2 spaces. This follows the [Prettier default](https://prettier.io/docs/en/options.html#tab-width), so has the highest likelihood of copying/pasting doing the "right thing". Otherwise, we'd have to configure Prettier in every CYF repo (and teach students how to do this in their own repos).

**Comment by textbook** [comment]
See CodeYourFuture/eslint-config-standard#12
