### ISSUE TITLE
Diagrams are broken in dark mode

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/syllabus#240]
**Describe the bug**

Tiniest bug. Diagrams are black on black in dark mode. You can see this on these pages:

https://syllabus.codeyourfuture.io/html-css/week-1/lesson
https://syllabus.codeyourfuture.io/js-core-2/week-3/lesson

**What is wrong with this content?**
Can't see the pictures.

**How could this be fixed?**
Ideally `filter: invert(1)` for monochrome diagrams on transparent backgrounds. If not possible, then a block white bg.

**Who else might need to know about this?**

Whoever has dealings with the front end.

**Comment by ChrisOwen101** [comment]
@grimxreaper Please do! Let me know if you have any problems getting setup.

**Comment by grimxreaper** [comment]
Cool! :) I've been looking through the code base and don't see where the react-toggle for dark mode is being coded, I thought they would be within the navbar in docusaurus.config.js but it isn't there. Do you mind pointing me in the right direction? @ChrisOwen101

**Comment by ChrisOwen101** [comment]
@grimxreaper To be honest - I'm not sure where I'd start this one from a CSS perspective. Maybe having a look through the Docusaurus Docs for some hints?

https://docusaurus.io/docs/2.0.0-alpha.75/

If not, adding a block white background to the images in the Issue description would be an acceptable fix for this.

**Comment by grimxreaper** [comment]
Okay great that's the approach I took since even after checking the Docusaurus docs and looking through the code again it wasn't obvious where that React-toggle for dark mode is. I just created a PR for this, thanks!
