### ISSUE TITLE
Add "Tech Test" type challenges to Syllabus

### ISSUE THREAD

**Issue by ChrisOwen101** [CodeYourFuture/syllabus#253]
**Which module(s) and week(s) does this change effect?**
Module(s): JS3? End of the course?

**What is the work that needs to be done?**

We've received a tech test from a partner organisation that had very reasonable requirements.

To prepare our students for these kind of tests, we could write up our own tests that have similar requirements. 

Roughly, these requirements are 

- Create a command line or small website 
- That fetches an API
- Manipulates the data (e.g. length of Y, total number of X, )
- Outputs the data to the terminal or website

There may be multiple steps to each of these e.g. fetch a list of cities, fetch a list of boroughs for each city

This challenge must have 

- Documentation for what the student must do
- A sample solution
- Stretch goals

**Why is this work important to do?**

Preparing our students for tech tests is important, we can also take the opportunity to give students feedback on their challenges which will prepare them even more.

**Additional context**

Speak to @ChrisOwen101 about the Tech Test we've been sent for inspiration

**Who might need to know about this change?**

@ChrisOwen101

**Comment by SallyMcGrath** [comment]
This issue may be superseded by introducing Codility testing per module

**Comment by 40thieves** [comment]
Discussed in global syllabus. We think there's quite of public resources now to find real tech tests, and so inventing our own doesn't seem worth it.

In addition, we don't think we have capacity to properly give feedback on any tech tests. However, trainees should have some familiarity thanks to Codility tests.
