### ISSUE TITLE
Convert JavaScript Core 1 Week 2 tests to use Jest

### ISSUE THREAD

**Issue by ChrisOwen101** [CodeYourFuture/syllabus#261]
**Which module(s) and week(s) does this change effect?**
Module(s): JS1
Week(s): 2

**What is the work that needs to be done?**

We should convert our tests in JS1-2 to use Jest instead of our custom test solution. 

**Why is this work important to do?**

Giving our students exposure to Jest will help them learn TDD and Unit Testing easier, later.

**Comment by illicitonion** [comment]
This was fixed by https://github.com/CodeYourFuture/JavaScript-Core-1-Coursework-Week2/pull/85
