### ISSUE TITLE
Rename master branch on https://github.com/CodeYourFuture/bikes-for-refugees to main

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/syllabus#263]
We should do this rename, partially because it's generally a good thing, and partially because our Git classes and cheat-sheet refer to `main` before we introduce branches. We should wait until no one has active PRs against this repo before doing so, to avoid accidentally messing things up for anyone.

**Comment by SallyMcGrath** [comment]
I've set up the main branch and I swapped it and then realised WM3 actually are still using this. So I swapped it back and will delete master in a few weeks TODO AUGUST 15
