### ISSUE TITLE
Use uuids instead of ids for albumsData

### ISSUE THREAD

**Issue by shen-sat** [CodeYourFuture/syllabus#267]
**Which module(s) and week(s) does this change effect?**
Module(s): Node
Week(s): 2

**What is the work that needs to be done?**
I was involved in a lesson (as a teaching assistant) and came across the following scenario which confused the students (as well as me!)

In [node week 2](https://github.com/CodeYourFuture/syllabus/blob/adbbdbc3c9e80eaad96ec74f1513893bb7d79a37/docs/node/week-2/lesson.md) we introduce a new variable `albumsData` which is an array of Beyonce albums.

When we make the request `GET /albums/10`, we ideally want to return the album with an id of 10. However, some students (and teachers) interpreted this as returning the album with an _index_ of 10 (because `albumsData` is an array).

In order to avoid this confusion (and to reflect real-world applications) we should change album ids into into uuids [as suggested here](https://github.com/CodeYourFuture/syllabus-archive/issues/473#issuecomment-846612266)

**Why is this work important to do?**
Less potential for students to be confused as to what purpose an id plays in fetching a record

**Additional context**
N/A

Thanks @textbook for your input and @40thieves for pointing me to the right repo :)

**Comment by ChrisOwen101** [comment]
Opened here @shen-sat 
https://github.com/CodeYourFuture/syllabus/pull/284
