### ISSUE TITLE
Add "Add Unit Test" Exercise to JS2-1

### ISSUE THREAD

**Issue by ChrisOwen101** [CodeYourFuture/syllabus#275]
**Which module(s) and week(s) does this change effect?**
Module(s): JS2
Week(s): 1 

**What is the work that needs to be done?**

By this point, the students will have had exposure to running tests and so the logical next step is for them to create their own tests that pass the code they've written.

The exercise should be added to 

https://github.com/CodeYourFuture/JavaScript-Core-2-Coursework-Week1

The example solution should also be added to 

https://github.com/CodeYourFuture/JavaScript-Core-2-Coursework-Week1-Solution

These new unit tests may simply be copy and pasting the current tests and changing the values to create new tests. 

**Why is this work important to do?**

Teaching students more about unit testing is important to do as they'll need to be able to show these skills 

**Who might need to know about this change?**

@CodeYourFuture/syllabus-team

**Comment by 40thieves** [comment]
I've drafted something in https://github.com/CodeYourFuture/JavaScript-Core-2-Coursework-Week1/pull/152. I think it would be useful to discuss at the TDD call next week, as I think it may need some supporting changes to the syllabus.

**Comment by 40thieves** [comment]
Done in https://github.com/CodeYourFuture/JavaScript-Core-2-Coursework-Week1/pull/152.
