### ISSUE TITLE
Add Jest and Unit Testing to JS2-3 Coursework

### ISSUE THREAD

**Issue by ChrisOwen101** [CodeYourFuture/syllabus#279]
**Which module(s) and week(s) does this change effect?**
Module(s): JS2
Week(s): 3

**What is the work that needs to be done?**

Adding Jest Unit Testing to JS2-3 is the next step to automating marking and teaching our students about unit testing

https://github.com/CodeYourFuture/JavaScript-Core-2-Coursework-Week3

- [x] Add unit testing for the Exericses
- [x] Add unit testing for the To Do

The Bike Project can be safely skipped

**Who need to know about this?**

@CodeYourFuture/syllabus-team

**Comment by SallyMcGrath** [comment]
#289

**Comment by 40thieves** [comment]
Linking it up: https://github.com/CodeYourFuture/JavaScript-Core-2-Coursework-Week3/pull/77 (I think this is the right one)
