### ISSUE TITLE
Add Jest and Unit Testing to JS2-3 Coursework - Alarm Clock

### ISSUE THREAD

**Issue by ChrisOwen101** [CodeYourFuture/syllabus#280]
**Which module(s) and week(s) does this change effect?**
Module(s): JS2
Week(s): 3

**What is the work that needs to be done?**

Add Jest and Unit Testing to the Alarm Clock project in JS2-3

https://github.com/CodeYourFuture/JavaScript-Core-2-Coursework-Week3/tree/main/mandatory/1-alarmclock

Be sure to also update the Solution repo

https://github.com/CodeYourFuture/JavaScript-Core-2-Coursework-Week3-Solution/tree/main/mandatory/1-alarmclock

**Why is this work important to do?**

Adding unit testing will make marking easier for our volunteers, provide better feedback for our students to know if the project is working and will take us one step closer to teaching Unit Testing properly.

**Additional context**

**Who might need to know about this change?**

@CodeYourFuture/syllabus-team

**Comment by SallyMcGrath** [comment]
#289
