### ISSUE TITLE
Add Jest and Unit Testing to JS2-Week4 Coursework - Quote generator & Slideshow project

### ISSUE THREAD

**Issue by ChrisOwen101** [CodeYourFuture/syllabus#282]
**Which module(s) and week(s) does this change effect?**
Module(s): JS2
Week(s): 3

**What is the work that needs to be done?**

Add Jest and Unit Testing to the Quote Generator project in JS2-3

https://github.com/CodeYourFuture/JavaScript-Core-2-Coursework-Week3/tree/main/mandatory/3-slideshow

Be sure to also update the Solution repo
https://github.com/CodeYourFuture/JavaScript-Core-2-Coursework-Week3-Solution/tree/main/mandatory/3-slideshow

**Why is this work important to do?**

Adding unit testing will make marking easier for our volunteers, provide better feedback for our students to know if the project is working and will take us one step closer to teaching Unit Testing properly.

**Additional context**

**Who might need to know about this change?**

@CodeYourFuture/syllabus-team

**Comment by SallyMcGrath** [comment]
#289 https://github.com/CodeYourFuture/syllabus/issues/289

**Comment by 40thieves** [comment]
The slideshow exercise has now moved to week 4: https://github.com/CodeYourFuture/JavaScript-Core-2-Coursework-Week4/tree/main/1-mandatory/3-slideshow

**Comment by 40thieves** [comment]
We should also make sure all the syllabus links point to the right place.

**Comment by Dedekind561** [comment]
Once this PR is in 👉 https://github.com/CodeYourFuture/JavaScript-Core-2-Coursework-Week4-Solution/pull/2 we can close this issue. ( It just adds the test suite into the solution repo )
