### ISSUE TITLE
Add Jest and Unit Testing to the To Do List project in JS2-2

### ISSUE THREAD

**Issue by ChrisOwen101** [CodeYourFuture/syllabus#288]
**Which module(s) and week(s) does this change effect?**
Module(s): JS2
Week(s): 2

**What is the work that needs to be done?**

Add Jest and Unit Testing to the To Do List project in JS2-2

https://github.com/CodeYourFuture/JavaScript-Core-2-Coursework-Week2/tree/main/projects/2-todo-list

Be sure to also update the Solution repo

https://github.com/CodeYourFuture/JavaScript-Core-2-Coursework-Week2-Solution/tree/main/projects/2-todo-list

**Why is this work important to do?**

Adding unit testing will make marking easier for our volunteers, provide better feedback for our students to know if the project is working and will take us one step closer to teaching Unit Testing properly.

**Additional context**

**Who might need to know about this change?**

@CodeYourFuture/syllabus-team

**Comment by SallyMcGrath** [comment]
#289

**Comment by SallyMcGrath** [comment]
is this merged @Dedekind561 ? Can you link the commit so I can close this issue?

**Comment by illicitonion** [comment]
Yeah, this was https://github.com/CodeYourFuture/JavaScript-Core-2-Coursework-Week2/pull/129 :)
