### ISSUE TITLE
Package.json is missing licence field JavaScript-Core-1-Coursework-Week1

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/syllabus#289]
https://github.com/CodeYourFuture/JavaScript-Core-1-Coursework-Week1/blob/master/package.json

It's not exactly a bug but  the package has no licence field so when trainees install Jest they get a warning and this makes them think it is broken

**What is wrong with this content?**

No licence field

**How could this be fixed?**

Add an open source licence. I can't find out how the syllabus is licensed but presumably MIT or ISC?

**Link to content**

https://github.com/CodeYourFuture/JavaScript-Core-1-Coursework-Week1/blob/master/package.json

**Additional context**

Our first class are using this right now :)

**Who else might need to know about this?**

TDD working group @ChrisOwen101 @illicitonion @mrbenbot

**Comment by illicitonion** [comment]
Aah good catch, I did not realise this would cause warnings!

https://syllabus.codeyourfuture.io/ says the syllabus is licensed with https://creativecommons.org/licenses/by-sa/4.0/

**Comment by 40thieves** [comment]
From what I understand, the NPM `license` field follows SPDX syntax: https://docs.npmjs.com/cli/v7/configuring-npm/package-json#license. So I believe the appropriate value would be CC-BY-4.0: https://spdx.org/licenses/CC-BY-4.0.html (assuming we want to follow the syllabus repo license)

**Comment by SallyMcGrath** [comment]
https://github.com/CodeYourFuture/CYF-Coursework-Template/commit/20f570449d31d5586f0bb9cee2d08d9e21f0d6e3
https://github.com/CodeYourFuture/JavaScript-Core-1-Coursework-Week1/commit/5c991372488f29758486b99079256a5ccb346f25
https://github.com/CodeYourFuture/JavaScript-Core-1-Coursework-Week2/commit/be773059a69416b12f7cf50572b5d60294369751
https://github.com/CodeYourFuture/JavaScript-Core-1-Coursework-Week3/commit/c40c819ed6d0a1522cf933125ff392c6803606dd
week 2 no jest
https://github.com/CodeYourFuture/JavaScript-Core-2-Coursework-Week3/commit/9beb2e131fd9927f00dfd87d6a3feaac4a496211

no jest in js3 yet
