### ISSUE TITLE
Minor coursework updates - remove optional and add Codewars

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/syllabus#297]
**Which module(s) and week(s) does this change effect?**
Module(s): all modules
Week(s): all weeks

**What is the work that needs to be done?**

Remove the (optional) flags from homework and reframe either as mandatory, recommended, or stretch
Set Codewars expectations and link to authored collections

**Why is this work important to do?**

1. We know that there is a correlation between trainees who struggle and trainees who skip all or most of the optional coursework. We are reframing that language in case we are giving the wrong signals.
2. We are removing the hard coded links to kata in the coursework and instead linking to the authored collections view on our CodeYourFuture account. This means we can easily change around kata and update them without troubling the syllabus.
3. We are setting expectations of levels and progress in Codewars now we have data on that

**Additional context**

**Who might need to know about this change?**

**Comment by illicitonion** [comment]
Did this mean to get closed? I don't think the "remove optional" did? @SallyMcGrath

**Comment by SallyMcGrath** [comment]
> Did this mean to get closed? I don't think the "remove optional" did? @SallyMcGrath

I did em and merged em as it's just a word change and the codewars stuff we already agreed on
