### ISSUE TITLE
Add JavaScript Core 1 Challenges

### ISSUE THREAD

**Issue by ChrisOwen101** [CodeYourFuture/syllabus#30]
**Which module(s) and week(s) does this change effect?**
Module(s): JS1
Week(s): 1/2/3

**What is the work that needs to be done?**

As a student I want to feel stretched and excited about solving interesting programming problems. I'd also like them to be targeted at my current development level.

The content for this module can be found [here](https://syllabus.codeyourfuture.io/js-core-1/index).

In this repository you will find a set of challenges that are appropriate for students who are studying JavaScript Core 1. You should open a pull request to that repository and with all of the challenge details.

https://github.com/CodeYourFuture/JavaScript-Core-1-Challenges

Make sure that you do not include any content that has not been covered in the three lessons in JavaScript Core 1.

**Why is this work important to do?**

Challenges are important for students development to give them time to practice what they are learning in class. They are also useful for teachers who can use the challenges in class to test students understanding. 

**Additional context**

This is a long running ticket - when you have completed it move it back into `Selected For Development`.

**Who might need to know about this change?**

@ChrisOwen101

**Comment by mickyginger** [comment]
These are some challenges I wrote for my cohorts at GA @ChrisOwen101, are they suitable? [js-challenges.zip](https://github.com/CodeYourFuture/syllabus/files/5307678/js-challenges.zip)

We also encouraged the students to sign up to [CodeWars](https://codewars.com) which we found reasonably easy for they to get up to speed with.

**Comment by SallyMcGrath** [comment]
I will take a look through this over the next fortnight to see if I have anything useful to add.

**Comment by SallyMcGrath** [comment]
https://github.com/CodeYourFuture/JavaScript-Core-1-Challenges
