### ISSUE TITLE
Write Github Action to run test suite on PRs

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/syllabus#300]
**Which module(s) and week(s) does this change affect?**
Module(s): JS-1 onwards
Week(s): all

**What is the work that needs to be done?**

Write a GH action to run all tests on PR on COURSEWORK REPOS

**Why is this work important to do?**

MVP: run tests on PR
Next step: produce stats or signals

**Additional context**

**Who might need to know about this change?**

TDD working group

**Comment by SallyMcGrath** [comment]
https://www.freecodecamp.org/news/what-are-github-actions-and-how-can-you-automate-tests-and-slack-notifications/

**Comment by SallyMcGrath** [comment]
@ChrisOwen101 @chewymeister

**Comment by chewymeister** [comment]
Is there anything I can do to help?

**Comment by SallyMcGrath** [comment]
> Is there anything I can do to help?

Oh I'm sorry, I think you are a victim of autocomplete! Carry on!
