### ISSUE TITLE
Draft Fundamentals Requirements sessions

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/syllabus#332]
2x 90 minute sessions covering Requirements + Iteration + Delivery with a focus on Requirements

Goal is to get enough of a skeleton in place that we can have a reasonable discussion about fleshing out the rest of the content.

**Comment by SallyMcGrath** [comment]
reminding you here we discussed:

- in groups, setting contradictory conditions and staging how to notice and deal with that situation

**Comment by illicitonion** [comment]
I've got the start of this in https://github.com/CodeYourFuture/syllabus/commits/fundamentals-requirements - comments/feedback/discussion super welcome!
