### ISSUE TITLE
Write Learning Objectives for revised Fundamentals

### ISSUE THREAD

**Issue by 40thieves** [CodeYourFuture/syllabus#343]
**Which module(s) and week(s) does this change affect?**
Module(s): Fundamentals
Week(s): 1 - 3

**What is the work that needs to be done?**

_This is a stub. @40thieves & @ChrisOwen101 will develop this further._

**Why is this work important to do?**

TODO

**Additional context**

TODO

**Comment by illicitonion** [comment]
Greg to fill in Blockly LOs

**Comment by gregdyke** [comment]
https://github.com/CodeYourFuture/syllabus/pull/389
