### ISSUE TITLE
Remove `var` from JS1 Week1 exercises

### ISSUE THREAD

**Issue by jstadnik** [CodeYourFuture/syllabus#357]
**Which module(s) and week(s) does this change affect?**
Module(s): JS-Core1
Week(s): Week 1

**What is the work that needs to be done?**

Replace `var` -> `let` everywhere.

**Why is this work important to do?**

The existing code in the exercises makes heavy use of `var`, which trainees are asked to avoid, so having it in the existing code and examples is confusing and awkward for TAs to explain.

**Additional context**

May want to check exercises still work after the change? Idk.

**Who might need to know about this change?**

**Comment by SallyMcGrath** [comment]
closed as split up into style guide violation tickets
