### ISSUE TITLE
Technical syllabus links are down 

### ISSUE THREAD

**Issue by zero-point** [CodeYourFuture/syllabus#428]
**Describe the bug**

I'm not sure this is the right place to report it, but the links to the technical content on the syllabus don't work. E.g. https://syllabus.codeyourfuture.io/html-css/index

**What is wrong with this content?**
Links not working 

**How could this be fixed?**
Update links I guess 

**Link to content**
https://syllabus.codeyourfuture.io/

**Additional context**

**Who else might need to know about this?**

**Comment by SallyMcGrath** [comment]
Hi hi Irina - can you tell me where this link is? (When I choose from the menu it works.) I found a broken link on https://syllabus.codeyourfuture.io/Overview -- is that where you where?

**Comment by zero-point** [comment]
Accessing the links from the Overview page https://syllabus.codeyourfuture.io/Overview

**Comment by SallyMcGrath** [comment]
fixed by #429
