### ISSUE TITLE
Document the goals of the Fundamentals course for volunteers

### ISSUE THREAD

**Issue by 40thieves** [CodeYourFuture/syllabus#446]
**Which module(s) and week(s) does this change affect?**
Module(s): Fundamentals
Week(s): All

**What is the work that needs to be done?**

We should add some documentation to the mentors notes of the Fundamentals course noting the overall goals:

- The course should be used to assess whether trainees are prepared for the full software development course
- The course should give trainees a "flavour" of the full software development course
- Trainees should learn useful development skills, even if they do not continue to the full software development course
- ...potentially some others? Open to suggestions on goals that I've missed

**Why is this work important to do?**

In order to teach the content effectively, volunteers should understand why the fundamentals course is part of the syllabus.

**Who might need to know about this change?**

@CodeYourFuture/global-syllabus

**Comment by gregdyke** [comment]
I think these are mostly already written in the main overview page - except the assessment part? Or that the assessment is intended to remove the need for interviews as they are are very ressource intensive

**Comment by SallyMcGrath** [comment]
https://www.youtube.com/watch?v=96Q-soVuYZw&list=PLozA7cloMbPgeWP7RI9p9HO2-mCFPxiWA&index=7
