### ISSUE TITLE
Review contributing guides

### ISSUE THREAD

**Issue by 40thieves** [CodeYourFuture/syllabus#46]
Module(s): N/A
Week(s): N/A

**What is the work that needs to be done?**

Inspired by [this change](https://github.com/CodeYourFuture/syllabus/pull/45), the contributing guide is now correctly linked from the README (thanks!)

However the link is to the [contributing guide](https://github.com/CodeYourFuture/syllabus/blob/master/docs/fundamentals/contributing.md) I wrote for the fundamentals module. The syllabus top-nav links to [a different guide](https://github.com/CodeYourFuture/syllabus/blob/master/docs/contributing/overview.md) (which looks like @ChrisOwen101 wrote).

I think it might also be worth noting that Github has some magic if the repo contains a `CONTRIBUTING.md` file in the root. We could consider moving our existing guides to this file.

**Why is this work important to do?**

Clarify what are the expectations of a contributor.

**Who might need to know about this change?**

@ChrisOwen101

**Comment by ChrisOwen101** [comment]
An issue with moving it to the "`CONTRIBUTING.md` file in the root" is that it won't be rendered by Docusaurus.

However, linking to that page from `CONTRIBUTING.md` is a good idea
