### ISSUE TITLE
Style Guide violation, to update

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/syllabus#568]
https://github.com/CodeYourFuture/syllabus/blob/02da63dbe1a20f8df0559074f4dac810e8af62a8/docs/js-core-2/mentor-guide.md?plain=1#L179

https://syllabus.codeyourfuture.io/guides/code-style-guide

Improper use of var

**Comment by MohitBansal321** [comment]
i think it need to change to let
if yes i will do it

**Comment by SallyMcGrath** [comment]
Hi! Please just take one ticket at a time. It's so great you're helping us and we are super grateful. Thank you!

**Comment by MohitBansal321** [comment]
I'm new to open source
okay I will generate another ticket when first ticket it approve 
Thank for helping me too
