### ISSUE TITLE
Add Sponsorship Banner to Front Page + Module Pages

### ISSUE THREAD

**Issue by ChrisOwen101** [CodeYourFuture/syllabus#57]
**What is the work that needs to be done?**

We get over 900 unique visitors a month and ~13K monthly page views. We could monetise this by offering a sponsorship package to the syllabus. This money would be ring-fenced to being spent onto on improving the syllabus.

**Why is this work important to do?**

Having dedicated funds to spend on the syllabus will improve it's quality and improve our students learning.

**Examples**

On the front page and in the sidebar here: https://material-ui.com/

**Design**

Something simple is fine. A button to a page with more information is more than enough.

**Comment by SallyMcGrath** [comment]
still pending with GHS

**Comment by SallyMcGrath** [comment]
I've set up Github Sponsors  with tiers - we don't currently offer anything specific for the money but we can do at some point if we have a good goal/idea.  Badging on github is automatic. Badging on the website is a service so will have to go through a different fundraising system - will pass it on to Hazel. Our bit is I think done.
