### ISSUE TITLE
Personal development 2 link is broken

### ISSUE THREAD

**Issue by FridIsar** [CodeYourFuture/syllabus#703]
**Describe the bug**
Broken link in the "Building a team" section of the [syllabus overview page](https://syllabus.codeyourfuture.io/overview).
**How could this be fixed?**
By replacing the link with the right one, or removing section if it's not part of the curriculum anymore.
**Link to content**
[Line that has to be updated](https://github.com/CodeYourFuture/syllabus/blob/80b38c99804e5012c40303975d2e9cf1cae46134/src/pages/overview.js#LL191C66-L191C66).

**Comment by 40thieves** [comment]
Looks like this is a casualty of the move of PD content into the main syllabus cc @esma-g / @kfklein15 

Given our move to the [new curriculum](https://github.com/codeyourfuture/curriculum), I'm leaning towards closing this out?

**Comment by esma-g** [comment]
Some links in the purple boxes on the overview page have been broken even before the PD content migration. I've recommended deleting the purple boxes to prevent further confusion, but this issue can be closed out without doing that if we will definitely stop using the old syllabus website with the new curriculum.

**Comment by kfklein15** [comment]
If we are using the new curriculum moving forward, we don't need to make changes on this one.
