### ISSUE TITLE
Fix ordering of data fetching exercises in React hotel homework

### ISSUE THREAD

**Issue by 40thieves** [CodeYourFuture/syllabus#75]
**Describe the bug**

In the React [hotel homework](https://github.com/codeyourfuture/cyf-hotel-react), exercise 15 is currently within the week 2 section. To complete this exercise, students must have knowledge of `useEffect` for data fetching, which is not taught until week 3 of the React module.

**How could this be fixed?**

The simple fix is to move exercise 15 into the week 3 section. However we may want to add an additional exercise to week 2 to make up for it. This should be considered at the same time as https://github.com/CodeYourFuture/syllabus/issues/73.

**Link to content**

Exercise 15: https://github.com/codeyourfuture/cyf-hotel-react#15-load-bookings-remotely

**Additional context**

Raised by Claire on Slack: https://codeyourfuture.slack.com/archives/C76GQDRH9/p1601283195001900.

**Comment by ChrisOwen101** [comment]
Adding an extra exercise in Week 2 is an option for this ticket - Talk to @40thieves

**Comment by 40thieves** [comment]
Did you intend on closing this @ChrisOwen101? AFAIK this is still a problem?

**Comment by 40thieves** [comment]
Oops nvm, just seen the PR
