### ISSUE TITLE
Feedback forms at end of lessons

### ISSUE THREAD

**Issue by ChrisOwen101** [CodeYourFuture/syllabus#81]
**Which module(s) and week(s) does this change effect?**
All Weeks and Modules

**Why is this work important to do?**

As our content is being used by more and more people around the world it's important that we receive feedback on what went well or poorly in the lesson.

**What is the work that needs to be done?**

**1. Create a Google Form**
Create a Google Form that has the following information

- Name (Optional)
- Module Name (Drop down)
- Week Name (Drop down)
- Teacher or Student (Checkbox)
- A series of questions about the quality of the content and what we can improve

**2. Create React Component**
A reusable Feedback component to embed at the end of each page to reduce duplication of code

**3. Embed to each week of the course**
A the end of each week we should embed this form to encourage people to complete it. 

_Idea_: Forms can be [pre-filled with data](https://www.labnol.org/prefilled-google-forms-200601#generate-the-prefilled-form-link). Could we do this to reduce errors?

**Who might need to know about this change?**

@nbogie

**Comment by nbogie** [comment]
Here's the one-minute-feedback form I used two years ago for React (and similar for Node and mongodb):
  https://docs.google.com/forms/d/1Bd15P9fNADySL-T_3aQcF4gfiYSodfZ0HOuPNxDWB74/edit

At its heart it was just: WWW & EBI:

Unscientifically designed questions: 
* What was one thing that you enjoyed?
* What didn't you understand or what did you have problems with?
* What could have been better about the way the session was taught?
